image_path = './data/image/'
resize = 256
val = 0.25
seed = 42
batch_size = 8
num_workers = 4
load_checkpoint = False
checkpoint = './checkpoint/last.pth'
save_model = './checkpoint'
lr = 1e-3
beta = 0.5
epochs = 300
val_epoch=5
style_image = './data/style3.jpg'
out_image = './out'
style_weight = 25.  # style2
